In [1]:
from typing import Union, List, Type, TypeVar, Generic
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
from fastapi.encoders import jsonable_encoder
from schemas import FpmkCreate
import schemas
import pandas as pd
import json
import numpy as np

In [31]:
t = pd.DataFrame(haha['data'])

In [32]:
t['date'] = pd.to_datetime(t['date'],format='%Y-%m-%d')

In [33]:
t

system subsystem  mileage unit  fpmk                      date
0    RSC       DOR     1000   km   7.0 2022-03-31 00:00:00+00:00
1    RSC       DOR     1500   km   5.0 2022-04-30 00:00:00+00:00
2    RSC       DOR     2000   km   6.0 2022-05-31 00:00:00+00:00
3    RSC       DOR     2300   km   7.0 2022-06-30 00:00:00+00:00
4    RSC       DOR     2700   km   4.0 2022-07-31 00:00:00+00:00
5    RSC       DOR     3200   km   5.0 2022-08-31 00:00:00+00:00
6    RSC       DOR     3400   km   3.0 2022-09-30 00:00:00+00:00
7    RSC       DOR     4000   km   2.0 2022-10-31 00:00:00+00:00

In [18]:
try:
    file = open(f"model_register/aad76f87.json")
except FileNotFoundError:
    print('GG')
haha = json.load(file)
data = pd.read_json(haha['data'], orient='records')
file.close()

ValueError: Invalid file path or buffer object type: <class 'list'>

In [2]:
import random

In [13]:
np.array([1])

array([1])

In [14]:
pd.Series(data=1)

0    1
dtype: int64

In [10]:
random_bits = random.getrandbits(32)
hash1 = "%4x" % random_bits
print(hash1)

a9e3e314


In [11]:
dictionary ={
    "name" : "sathiyajith",
    "rollno" : 56,
    "cgpa" : 8.6,
    "phonenumber" : "9976770500"
}

In [12]:
with open(f"{hash1}.json", "w") as outfile:
    json.dump(dictionary, outfile)

In [2]:
import sys

In [3]:
ScalerType = TypeVar("ScalerType", bound=Union[MinMaxScaler, RobustScaler, StandardScaler])

In [24]:
class CustomisedScaler(Generic[ScalerType]):
    def __init__(self, scaler_name: str):
        self.scaler = getattr(sys.modules[__name__], scaler_name)()

    def transform(self, fpmk_train: List[FpmkCreate], fpmk_in: List[FpmkCreate]) -> List[FpmkCreate]:
        fpmk_hist = pd.DataFrame(data=jsonable_encoder(fpmk_train))
        fpmk_hist['fpmk'] = self.scaler.fit(fpmk_hist['fpmk'].to_numpy().reshape(-1, 1))
        fpmk_out = pd.DataFrame(data=jsonable_encoder(fpmk_in))
        fpmk_out['fpmk'] = self.scaler.transform(fpmk_out['fpmk'].to_numpy().reshape(-1, 1))
        res = []
        for item in json.loads(fpmk_out.to_json(orient='records')):
            res.append(FpmkCreate(**item))
        return res

    def inverse_transform(self, fpmk_train: List[FpmkCreate], fpmk_in: List[FpmkCreate]) -> List[FpmkCreate]:
        fpmk_hist = pd.DataFrame(data=jsonable_encoder(fpmk_train))
        fpmk_hist['fpmk'] = self.scaler.fit(fpmk_hist['fpmk'].to_numpy().reshape(-1, 1))
        fpmk_out = pd.DataFrame(data=jsonable_encoder(fpmk_in))
        fpmk_out['fpmk'] = self.scaler.inverse_transform(fpmk_out['fpmk'].to_numpy().reshape(-1, 1))
        res = []
        for item in json.loads(fpmk_out.to_json(orient='records')):
            res.append(FpmkCreate(**item))
        return res

In [5]:
data_in = pd.read_csv('sample/sample.csv')

In [6]:
data_in['fpmk'].to_numpy().reshape(-1,1)

array([[7],
       [5],
       [6],
       [7],
       [4],
       [5],
       [3],
       [2]], dtype=int64)

In [7]:
res = []

In [8]:
for item in json.loads(data_in.to_json(orient='records')):
    res.append(FpmkCreate(**item))

In [25]:
cs = CustomisedScaler('MinMaxScaler')

In [26]:
res

[FpmkCreate(system='RSC', subsystem='DOR', mileage=1000, unit='km', fpmk=7.0, date=datetime.date(2022, 3, 31)),
 FpmkCreate(system='RSC', subsystem='DOR', mileage=1500, unit='km', fpmk=5.0, date=datetime.date(2022, 4, 30)),
 FpmkCreate(system='RSC', subsystem='DOR', mileage=2000, unit='km', fpmk=6.0, date=datetime.date(2022, 5, 31)),
 FpmkCreate(system='RSC', subsystem='DOR', mileage=2300, unit='km', fpmk=7.0, date=datetime.date(2022, 6, 30)),
 FpmkCreate(system='RSC', subsystem='DOR', mileage=2700, unit='km', fpmk=4.0, date=datetime.date(2022, 7, 31)),
 FpmkCreate(system='RSC', subsystem='DOR', mileage=3200, unit='km', fpmk=5.0, date=datetime.date(2022, 8, 31)),
 FpmkCreate(system='RSC', subsystem='DOR', mileage=3400, unit='km', fpmk=3.0, date=datetime.date(2022, 9, 30)),
 FpmkCreate(system='RSC', subsystem='DOR', mileage=4000, unit='km', fpmk=2.0, date=datetime.date(2022, 10, 31))]

In [27]:
t = cs.transform(fpmk_train=res, fpmk_in=res)

In [28]:
cs.inverse_transform(fpmk_train=res, fpmk_in=t)

[FpmkCreate(system='RSC', subsystem='DOR', mileage=1000, unit='km', fpmk=7.0, date=datetime.date(2022, 3, 31)),
 FpmkCreate(system='RSC', subsystem='DOR', mileage=1500, unit='km', fpmk=5.0, date=datetime.date(2022, 4, 30)),
 FpmkCreate(system='RSC', subsystem='DOR', mileage=2000, unit='km', fpmk=6.0, date=datetime.date(2022, 5, 31)),
 FpmkCreate(system='RSC', subsystem='DOR', mileage=2300, unit='km', fpmk=7.0, date=datetime.date(2022, 6, 30)),
 FpmkCreate(system='RSC', subsystem='DOR', mileage=2700, unit='km', fpmk=4.0, date=datetime.date(2022, 7, 31)),
 FpmkCreate(system='RSC', subsystem='DOR', mileage=3200, unit='km', fpmk=5.0, date=datetime.date(2022, 8, 31)),
 FpmkCreate(system='RSC', subsystem='DOR', mileage=3400, unit='km', fpmk=3.0, date=datetime.date(2022, 9, 30)),
 FpmkCreate(system='RSC', subsystem='DOR', mileage=4000, unit='km', fpmk=2.0, date=datetime.date(2022, 10, 31))]

In [24]:
from typing import List, Union

In [27]:
fpmk_1 = schemas.Fpmk(date='2021-03-31', fpmk=12, subsystem='DOR', system='RSC')

ValidationError: 2 validation errors for Fpmk
mileage
  field required (type=value_error.missing)
unit
  field required (type=value_error.missing)

In [ ]:
fpmk_2 = schemas.Fpmk(date='2021-04-30', fpmk=13, subsystem='DOR', system='RSC')

In [18]:
fpmk_3 = schemas.Fpmk(date='2021-05-31', fpmk=18, subsystem='DOR', system='RSC')

NameError: name 'schemas' is not defined

In [9]:
fpmk_list = [fpmk_1, fpmk_2, fpmk_3]

In [50]:
import pandas as pd
import json

In [51]:
df = pd.DataFrame(data=jsonable_encoder(fpmk_list))

In [52]:
df['date'] = pd.to_datetime(df['date'])

In [64]:
df['date']

(3,)

In [53]:
res = []
for item in json.loads(df.to_json(orient='records')):
    res.append(schemas.Fpmk(**item))

In [54]:
res

[Fpmk(system='RSC', subsystem='DOR', fpmk=12, date=datetime.date(2021, 3, 31)),
 Fpmk(system='RSC', subsystem='DOR', fpmk=13, date=datetime.date(2021, 4, 30)),
 Fpmk(system='RSC', subsystem='DOR', fpmk=18, date=datetime.date(2021, 5, 31))]

In [59]:
'system' in df.columns

True

In [58]:
for c in df.columns:
    print(c)

system
subsystem
fpmk
date


In [15]:
df.set_index('date', inplace=True)

In [16]:
df = df.asfreq('M')

In [90]:
df['system'].mode().values[0]

'RSC'

In [18]:
df['fpmk'].index.shift(1)[-1]

Timestamp('2021-06-30 00:00:00', freq='M')

In [39]:
res = df['fpmk']

In [40]:
res

date
2021-03-31    12
2021-04-30    13
2021-05-31    18
Freq: M, Name: fpmk, dtype: int64

In [28]:
res = pd.DataFrame(res, columns=['fpmk'])

In [47]:
res

date
2021-03-31    12
2021-04-30    13
2021-05-31    18
Freq: M, Name: fpmk, dtype: int64

In [34]:
res = res.reset_index()

In [82]:
res['sys_cd'] = 'RSC'

In [36]:
res.index.values

array([0, 1, 2], dtype=int64)

In [1]:
import numpy as np

In [25]:
np.log(30)

3.4011973816621555

In [27]:
res.index.values

array(['2021-03-31T00:00:00.000000000', '2021-04-30T00:00:00.000000000',
       '2021-05-31T00:00:00.000000000'], dtype='datetime64[ns]')

In [43]:
[x for x in range(1, 6)]

[1, 2, 3, 4, 5]

In [66]:
1.1**10 * 25000

64843.56150250006

In [85]:
np.arange(3, 6).reshape(-1, 1)

array([[3],
       [4],
       [5]])

In [122]:
base_uri = 'https://mvp-zr5ic3h7sq-uc.a.run.app' # https://mvp-zr5ic3h7sq-as.a.run.app
train_model_api = '/api/v1/lt_reliability/train'
forecast_cycle_api = '/api/v1/lt_reliability/forecast_by_cycles'
forecast_mileage_api = '/api/v1/lt_reliability/forecast_by_mileage'
data_sourcing_batch_api = '/api/v1/data_sourcing/batch'
data_sourcing_trx_api = '/api/v1/data_sourcing/transaction'
query_all_hist_api = '/api/v1/data_sourcing/history'

In [36]:
import requests
import json
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [42]:
pd.options.plotting.backend = "plotly"

In [18]:
# upload_response = requests.post(base_uri+data_sourcing_batch_api, files={'file': uploaded_file})
all_data = requests.get(base_uri+query_all_hist_api)

In [79]:
fpmk_hist['date'] = pd.to_datetime(fpmk_hist['date'])

In [85]:
import datetime

In [91]:
type(fpmk_hist['date'].min())

pandas._libs.tslibs.timestamps.Timestamp

In [47]:
fpmk_hist.set_index('date')[['fpmk','mileage']].plot()

In [73]:
data = {
    'system': 'RSC',
    'subsystem': 'DOR',
    'mileage': 4200,
    'unit': 'km',
    'fpmk': 7,
    'date': pd.to_datetime('2022-11-30').strftime("%Y-%m-%d")
}
response = requests.post(base_uri+data_sourcing_trx_api, params=data)

In [74]:
data

{'system': 'RSC',
 'subsystem': 'DOR',
 'mileage': 4200,
 'unit': 'km',
 'fpmk': 7,
 'date': '2022-11-30'}

In [100]:
fpmk_hist['date'] = fpmk_hist['date'].dt.strftime('%Y-%m-%d')

In [108]:
train_data_list = []
for item in json.loads(fpmk_hist.to_json(orient='records')):
    train_data_list.append(item)
response = requests.post(base_uri+train_model_api, json=train_data_list,params={'design_oem_mileage': 10000})

In [ ]:
dc4b4337

In [114]:
json.loads(response.content)

{'best_params': {'a': 1.0,
  'b': 0.301,
  'k': 0.7030500018728786,
  'logc': None,
  'logm': -13.32583668540579},
 'model_id': 'dc4b4337'}

In [123]:
response = requests.post(base_uri+forecast_cycle_api, params={"mod_id":"dc4b4337", "no_fcst_cycles":100})

In [124]:
response.status_code

200

In [126]:
fpmk_fcst = pd.DataFrame(data=json.loads(response.content))

In [127]:
fpmk_fcst

system subsystem  mileage unit      fpmk        date
0     RSC       DOR     4360   km  5.690009  2022-11-30
1     RSC       DOR     4771   km  5.999049  2022-12-31
2     RSC       DOR     5182   km  6.352331  2023-01-31
3     RSC       DOR     5592   km  6.759774  2023-02-28
4     RSC       DOR     6003   km  7.238438  2023-03-31
..    ...       ...      ...  ...       ...         ...
95    RSC       DOR    43378   km       NaN  2030-10-31
96    RSC       DOR    43789   km       NaN  2030-11-30
97    RSC       DOR    44200   km       NaN  2030-12-31
98    RSC       DOR    44610   km       NaN  2031-01-31
99    RSC       DOR    45021   km       NaN  2031-02-28

[100 rows x 6 columns]

In [125]:
response.content

b'[{"system":"RSC","subsystem":"DOR","mileage":4360,"unit":"km","fpmk":5.6900085845,"date":"2022-11-30"},{"system":"RSC","subsystem":"DOR","mileage":4771,"unit":"km","fpmk":5.9990486603,"date":"2022-12-31"},{"system":"RSC","subsystem":"DOR","mileage":5182,"unit":"km","fpmk":6.352331079,"date":"2023-01-31"},{"system":"RSC","subsystem":"DOR","mileage":5592,"unit":"km","fpmk":6.7597735394,"date":"2023-02-28"},{"system":"RSC","subsystem":"DOR","mileage":6003,"unit":"km","fpmk":7.2384377802,"date":"2023-03-31"},{"system":"RSC","subsystem":"DOR","mileage":6414,"unit":"km","fpmk":7.8088022684,"date":"2023-04-30"},{"system":"RSC","subsystem":"DOR","mileage":6825,"unit":"km","fpmk":8.5023337414,"date":"2023-05-31"},{"system":"RSC","subsystem":"DOR","mileage":7235,"unit":"km","fpmk":9.3650934527,"date":"2023-06-30"},{"system":"RSC","subsystem":"DOR","mileage":7646,"unit":"km","fpmk":10.4800728316,"date":"2023-07-31"},{"system":"RSC","subsystem":"DOR","mileage":8057,"unit":"km","fpmk":11.98435120

In [75]:
response.content

b'[{"system":"RSC","subsystem":"DOR","mileage":1000,"unit":"km","fpmk":7.0,"date":"2022-03-31"},{"system":"RSC","subsystem":"DOR","mileage":1500,"unit":"km","fpmk":5.0,"date":"2022-04-30"},{"system":"RSC","subsystem":"DOR","mileage":2000,"unit":"km","fpmk":6.0,"date":"2022-05-31"},{"system":"RSC","subsystem":"DOR","mileage":2300,"unit":"km","fpmk":7.0,"date":"2022-06-30"},{"system":"RSC","subsystem":"DOR","mileage":2700,"unit":"km","fpmk":4.0,"date":"2022-07-31"},{"system":"RSC","subsystem":"DOR","mileage":3200,"unit":"km","fpmk":5.0,"date":"2022-08-31"},{"system":"RSC","subsystem":"DOR","mileage":3400,"unit":"km","fpmk":3.0,"date":"2022-09-30"},{"system":"RSC","subsystem":"DOR","mileage":4000,"unit":"km","fpmk":2.0,"date":"2022-10-31"},{"system":"RSC","subsystem":"DOR","mileage":4200,"unit":"km","fpmk":7.0,"date":"2022-11-30"}]'

In [60]:
all_data = requests.get(base_uri+query_all_hist_api)
fpmk_hist = pd.DataFrame(data=json.loads(all_data.content))

fig = make_subplots(rows=2, cols=1,shared_xaxes=True,)
fig.add_trace(go.Bar(
    x = fpmk_hist['date'],
    y =fpmk_hist['fpmk'], name='fpmk'), row=1, col=1)
fig.add_trace(go.Scatter(
    x = fpmk_hist['date'],
    y = fpmk_hist['mileage'],
    mode='lines',
    name='mileage'
), row=2, col=1)
# edit axis labels
fig['layout']['yaxis']['title']='FPMK'
fig['layout']['yaxis2']['title']='Mileage(km)'
fig.show()